"""terms accepted timestamp on user

Revision ID: 03b5135931ae
Revises: 20963432ba19
Create Date: 2026-09-01 17:43:35.843456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b5135931ae'
down_revision: Union[str, None] = '20963432ba19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'terms_accepted_at')
    # ### end Alembic commands ###
