"""disconnected_at on garmin account

Revision ID: 050656efb2dd
Revises: 03b5135931ae
Create Date: 2026-09-01 18:06:17.405729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050656efb2dd'
down_revision: Union[str, None] = '03b5135931ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garmin_account', sa.Column('disconnected_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garmin_account', 'disconnected_at')
    # ### end Alembic commands ###
