"""scope activity uniqueness to user

Revision ID: 20963432ba19
Revises: 7ba144568a45
Create Date: 2026-08-31 17:05:08.560961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20963432ba19'
down_revision: Union[str, None] = '7ba144568a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_activity_garmin_activity_id', 'activity', type_='unique')
    op.create_unique_constraint('uq_activity_user_garmin_activity_id', 'activity', ['user_id', 'garmin_activity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_activity_user_garmin_activity_id', 'activity', type_='unique')
    op.create_unique_constraint('uq_activity_garmin_activity_id', 'activity', ['garmin_activity_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
