"""exercise sets on activity

Revision ID: 6671f49c7a69
Revises: 050656efb2dd
Create Date: 2026-09-01 19:02:14.402907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6671f49c7a69'
down_revision: Union[str, None] = '050656efb2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('exercise_sets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'exercise_sets')
    # ### end Alembic commands ###
