"""chat_message table, vo2max, daily summary hour

Revision ID: 7ba144568a45
Revises: ef05c35e6f14
Create Date: 2026-08-31 16:53:05.829629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # needed for sqlmodel.sql.sqltypes.AutoString - autogenerate doesn't add this import by itself


# revision identifiers, used by Alembic.
revision: str = '7ba144568a45'
down_revision: Union[str, None] = 'ef05c35e6f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_created_at'), 'chat_message', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_message_user_id'), 'chat_message', ['user_id'], unique=False)
    op.add_column('daily_metric', sa.Column('vo2_max', sa.Float(), nullable=True))
    op.add_column('daily_metric', sa.Column('fitness_age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('daily_summary_hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'daily_summary_hour')
    op.drop_column('daily_metric', 'fitness_age')
    op.drop_column('daily_metric', 'vo2_max')
    op.drop_index(op.f('ix_chat_message_user_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_created_at'), table_name='chat_message')
    op.drop_table('chat_message')
    # ### end Alembic commands ###
