"""training_plan table

Revision ID: 922ec3cff608
Revises: 6671f49c7a69
Create Date: 2026-09-06 07:30:00.000000

Written by hand rather than autogenerated. docker-compose.prod.yml carries no
bind mounts on purpose - the image holds the code, so what runs is exactly
what was built - which means `alembic revision --autogenerate` on the server
writes the file inside a container that `run --rm` then deletes. Migrations
get generated locally (or written out, as here) and only ever applied in
production.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # needed for sqlmodel.sql.sqltypes.AutoString - autogenerate doesn't add this import by itself


# revision identifiers, used by Alembic.
revision: str = '922ec3cff608'
down_revision: Union[str, None] = '6671f49c7a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'training_plan',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('discipline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        # One current plan per discipline: saving a swim plan must replace the
        # previous swim plan and leave the running plan untouched.
        sa.UniqueConstraint('user_id', 'discipline', name='uq_training_plan_user_discipline'),
    )
    op.create_index(op.f('ix_training_plan_user_id'), 'training_plan', ['user_id'], unique=False)
    op.create_index(op.f('ix_training_plan_discipline'), 'training_plan', ['discipline'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_training_plan_discipline'), table_name='training_plan')
    op.drop_index(op.f('ix_training_plan_user_id'), table_name='training_plan')
    op.drop_table('training_plan')
