"""add daily_metric and activity tables

Revision ID: ca83bd392cce
Revises: a37848965653
Create Date: 2026-08-25 12:30:46.482570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # needed for sqlmodel.sql.sqltypes.AutoString - autogenerate doesn't add this import by itself
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca83bd392cce'
down_revision: Union[str, None] = 'a37848965653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garmin_activity_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Float(), nullable=True),
    sa.Column('max_heart_rate', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garmin_activity_id', name='uq_activity_garmin_activity_id')
    )
    op.create_index(op.f('ix_activity_start_time'), 'activity', ['start_time'], unique=False)
    op.create_index(op.f('ix_activity_user_id'), 'activity', ['user_id'], unique=False)
    op.create_table('daily_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('min_heart_rate', sa.Integer(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.Integer(), nullable=True),
    sa.Column('active_calories', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('floors_climbed', sa.Float(), nullable=True),
    sa.Column('avg_stress_level', sa.Integer(), nullable=True),
    sa.Column('max_stress_level', sa.Integer(), nullable=True),
    sa.Column('body_battery_high', sa.Integer(), nullable=True),
    sa.Column('body_battery_low', sa.Integer(), nullable=True),
    sa.Column('moderate_intensity_minutes', sa.Integer(), nullable=True),
    sa.Column('vigorous_intensity_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('deep_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('light_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('rem_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('awake_minutes', sa.Integer(), nullable=True),
    sa.Column('avg_sleep_respiration', sa.Float(), nullable=True),
    sa.Column('avg_sleep_stress', sa.Float(), nullable=True),
    sa.Column('avg_hrv', sa.Integer(), nullable=True),
    sa.Column('hrv_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_metric_user_date')
    )
    op.create_index(op.f('ix_daily_metric_date'), 'daily_metric', ['date'], unique=False)
    op.create_index(op.f('ix_daily_metric_user_id'), 'daily_metric', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_metric_user_id'), table_name='daily_metric')
    op.drop_index(op.f('ix_daily_metric_date'), table_name='daily_metric')
    op.drop_table('daily_metric')
    op.drop_index(op.f('ix_activity_user_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_start_time'), table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
